//===----------------------------------------------------------------------===//
//
// This source file is part of the Netbot open source project
//
// Copyright (c) 2021 Junfeng Zhang. and the Netbot project authors
// Licensed under Apache License v2.0
//
// See LICENSE for license information
// See CONTRIBUTORS.txt for the list of Netbot project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension ClientGreetingTests {

   static var allTests : [(String, (ClientGreetingTests) -> () throws -> Void)] {
      return [
                ("testReadFromByteBuffer", testReadFromByteBuffer),
                ("testWriteToByteBuffer", testWriteToByteBuffer),
           ]
   }
}

