//===----------------------------------------------------------------------===//
//
// This source file is part of the Netbot open source project
//
// Copyright © 2019 Netbot Ltd. and the Netbot project authors
// Licensed under Apache License v2.0
//
// See LICENSE for license information
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// NIOSecurityTests+XCTest.swift
//

import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension NIOSecurityTests {

   static var allTests : [(String, (NIOSecurityTests) -> () throws -> Void)] {
      return [
                ("testSALSA", testSALSA),
                ("testRC4", testRC4),
                ("testRC4MD5", testRC4MD5),
                ("testBlowfish", testBlowfish),
                ("testAES128CFB", testAES128CFB),
                ("testAES192CFB", testAES192CFB),
                ("testAES256CFB", testAES256CFB),
                ("testAES128CTR", testAES128CTR),
                ("testAES192CTR", testAES192CTR),
                ("testAES256CTR", testAES256CTR),
                ("testCAMELLIA128CFB", testCAMELLIA128CFB),
                ("testCAMELLIA192CFB", testCAMELLIA192CFB),
                ("testCAMELLIA256CFB", testCAMELLIA256CFB),
                ("testCHACHA20", testCHACHA20),
                ("testXCHACHA20", testXCHACHA20),
                ("testCHACHA20IETF", testCHACHA20IETF),
                ("testAES128GCM", testAES128GCM),
                ("testAES192GCM", testAES192GCM),
                ("testAES256GCM", testAES256GCM),
                ("testCHACHA20Poly1305", testCHACHA20Poly1305),
                ("testCHACHA20IETFPoly1305", testCHACHA20IETFPoly1305),
                ("testXCHACHA20IETFPoly1305", testXCHACHA20IETFPoly1305),
           ]
   }
}

