services:

  runtime-setup:
    image: swift-nio-netbot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        swift_version: "5.7"

  common:
    &common
    image: swift-nio-netbot
    depends_on: [ runtime-setup ]
    volumes:
      - ..:/code:z
    working_dir: /code
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  generate:
    <<: *common
    command: /bin/bash scripts/generate_boilerplate_files.sh

  test:
    <<: *common
    depends_on: [generate]
    command: /bin/bash -xcl "swift test --sanitize thread -Xswiftc -warnings-as-errors"

  # util
  shell:
    <<: *common
    entrypoint: /bin/bash

  formatting:
    <<: *common
    entrypoint: /bin/bash -xcl "swift-format --configuration ./.swift-format --in-place --recursive --parallel ./Sources ./Tests"
