version: "3"

services:

  runtime-setup:
    image: swift-netbot-core:default
    build:
      context: .
      dockerfile: Dockerfile

  common:
    &common
    image: swift-netbot-core:default
    depends_on: [ runtime-setup ]
    volumes:
      - ..:/code:z
    working_dir: /code
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  soundness:
    <<: *common
    command: /bin/bash -xcl "swift --version && uname -a && ./scripts/soundness.sh"

  test:
    <<: *common
    command: /bin/bash -xcl "swift $${SWIFT_TEST_VERB-test} $${WARN_AS_ERROR_ARG-} $${SANITIZER_ARG-} $${IMPORT_CHECK_ARG-}"

  # util
  shell:
    <<: *common
    entrypoint: /bin/bash
