//===----------------------------------------------------------------------===//
//
// This source file is part of the Netbot open source project
//
// Copyright © 2019 Netbot Ltd. and the Netbot project authors
// Licensed under Apache License v2.0
//
// See LICENSE for license information
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// HTTPProxyProtocolTests+XCTest.swift
//

import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///
/*
extension HTTPProxyProtocolTests {

   static var allTests : [(String, (HTTPProxyProtocolTests) -> () throws -> Void)] {
      return [
                ("testUpgradeWithoutSendHttpEndPart", testUpgradeWithoutSendHttpEndPart),
                ("testUpgradeHandlerBufferOnUnexpectedOrdering", testUpgradeHandlerBufferOnUnexpectedOrdering),
                ("testUpgradeWhenBuildProxyResponseFailed", testUpgradeWhenBuildProxyResponseFailed),
                ("testSimpleSucceedUpgradeHandler", testSimpleSucceedUpgradeHandler),
                ("testUpgradeFiresUserEvent", testUpgradeFiresUserEvent),
           ]
   }
}

*/
