//===----------------------------------------------------------------------===//
//
// This source file is part of the Netbot open source project
//
// Copyright (c) 2021 Junfeng Zhang. and the Netbot project authors
// Licensed under Apache License v2.0
//
// See LICENSE for license information
// See CONTRIBUTORS.txt for the list of Netbot project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension NetAddressTests {

   static var allTests : [(String, (NetAddressTests) -> () throws -> Void)] {
      return [
                ("testEquatableWorks", testEquatableWorks),
                ("testNetAddressErrorEqutable", testNetAddressErrorEqutable),
                ("testApplyingDomainPortAddress", testApplyingDomainPortAddress),
                ("testApplyingIPv4SocketAddress", testApplyingIPv4SocketAddress),
                ("testApplyingIPv6SocketAddress", testApplyingIPv6SocketAddress),
                ("testRejectWrongAddressType", testRejectWrongAddressType),
                ("testReadAddressButBufferIsNotEnoughToReadAsNetAddress", testReadAddressButBufferIsNotEnoughToReadAsNetAddress),
                ("testReadAddressButBufferIsEmpty", testReadAddressButBufferIsEmpty),
                ("testReadIPv4Address", testReadIPv4Address),
                ("testReadIPv6Address", testReadIPv6Address),
                ("testReadDomain", testReadDomain),
           ]
   }
}

