//===----------------------------------------------------------------------===//
//
// This source file is part of the Netbot open source project
//
// Copyright (c) 2021 Junfeng Zhang. and the Netbot project authors
// Licensed under Apache License v2.0
//
// See LICENSE for license information
// See CONTRIBUTORS.txt for the list of Netbot project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension ProxyPolicyTests {

   static var allTests : [(String, (ProxyPolicyTests) -> () throws -> Void)] {
      return [
                ("testParsingDirectPolicy", testParsingDirectPolicy),
                ("testDirectPolicyEncoding", testDirectPolicyEncoding),
                ("testParsingRejectPolicy", testParsingRejectPolicy),
                ("testRejectPolicyEncoding", testRejectPolicyEncoding),
                ("testParsingRejectTinyGifPolicy", testParsingRejectTinyGifPolicy),
                ("testRejectTinyGifPolicyEncoding", testRejectTinyGifPolicyEncoding),
                ("testParsingShadowsocksPolicy", testParsingShadowsocksPolicy),
                ("testParsingShadowsocksPolicyWithStringThatMissingBoolValueField", testParsingShadowsocksPolicyWithStringThatMissingBoolValueField),
                ("testParsingShadowsocksPolicyFieldRequires", testParsingShadowsocksPolicyFieldRequires),
                ("testShadowoscksPolicyEncoding", testShadowoscksPolicyEncoding),
                ("testParsingSOCKS5Policy", testParsingSOCKS5Policy),
                ("testParsingSOCKS5PolicyFieldRequires", testParsingSOCKS5PolicyFieldRequires),
                ("testSOCKS5PolicyEncoding", testSOCKS5PolicyEncoding),
                ("testParsingSOCKS5TLSPolicy", testParsingSOCKS5TLSPolicy),
                ("testParsingSOCKS5TLSPolicyFieldRequires", testParsingSOCKS5TLSPolicyFieldRequires),
                ("testSOCKS5TLSPolicyEncoding", testSOCKS5TLSPolicyEncoding),
                ("testParsingHTTPSProxyPolicy", testParsingHTTPSProxyPolicy),
                ("testParsingHTTPSPolicyFieldRequires", testParsingHTTPSPolicyFieldRequires),
                ("testHTTPSPolicyEncoding", testHTTPSPolicyEncoding),
                ("testParsingHTTPProxyPolicy", testParsingHTTPProxyPolicy),
                ("testParsingHTTPPolicyFieldRequires", testParsingHTTPPolicyFieldRequires),
                ("testHTTPPolicyEncoding", testHTTPPolicyEncoding),
                ("testParsingProxyPolicy", testParsingProxyPolicy),
                ("testProxyPolicyEncoding", testProxyPolicyEncoding),
           ]
   }
}

