name: Pull Request Validation (Soundness)

on:
  pull_request:
  push:
    branches:
      - main
      - release/*

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      api_breakage_check_enabled: false
      license_header_check_enabled: true
      license_header_check_project_name: "Netbot"
      python_lint_check_enabled: false
