name: Pull Request Validation (Soundness)

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  soundness:
    name: pull request validation (soundness)
    runs-on: ubuntu-22.04

    steps:
      - name: Setup Python...
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Checkout repository...
        uses: actions/checkout@v3
      
      - name: Run soundness checking...
        run: bash scripts/soundness.sh
