name: Pull Request Validation (Soundness)

on:
  pull_request:
  push:
    branches:
      - main
      - release/*

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      api_breakage_check_enabled: false
      license_header_check_enabled: false
      license_header_check_project_name: "Netbot"
      python_lint_check_enabled: false

  license-header-check:
    name: License headers check
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout repository...
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run license header check
        env:
          ORGANIZATION: Junfeng Zhang
          PROJECT_NAME: Netbot
        run: bash scripts/check-license-header.sh
