name: Soundness

on:
  workflow_call:

jobs:
  soundness:
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      api_breakage_check_enabled: false
      license_header_check_project_name: "Netbot"
      python_lint_check_enabled: false
