name: Pull Request Validation (CI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: pull request validation (${{ matrix.swift-version }}-${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-22.04, macos-12]
        swift-version: ["5.7"]
        
    steps:
      - name: Setup Swift...
        uses: swift-actions/setup-swift@v1
        with: 
          swift-version: ${{ matrix.swift-version }}

      - name: Checkout repository...
        uses: actions/checkout@v3
      
      - name: Build and test...
        run: swift test --sanitize thread -Xswiftc -warnings-as-errors
