name: Pull Request Validation (CI)

on:
  pull_request:
  push:
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit tests validation (${{ matrix.swift-version }}-${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14]
        swift-version: ["5.9", "5.10", "6.0"]

    steps:
      - name: Checkout repository...
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Mark the workspace as safe
        # https://github.com/actions/checkout/issues/766
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Setup swift ${{ matrix.swift-version  }}
        uses: hdtls/setup-swift@main
        with:
          swift-version: ${{matrix.swift-version}}

      - name: Unit tests...
        if: ${{ matrix.swift-version == 5.9 || matrix.swift-version == 5.10 }}
        run: swift test -Xswiftc -warnings-as-errors --explicit-target-dependency-import-check error

      - name: Unit tests...
        if: ${{ matrix.swift-version == 6.0 }}
        run: swift test --explicit-target-dependency-import-check error
