name: Pull Request Validation (CI)

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: pull request validation (${{ matrix.swift-version }}-${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-22.04, macos-12]
        swift-version: ["5.7", "5.8"]
        
    steps:
      - name: Checkout repository...
        uses: actions/checkout@v3

      - name: Setup swift ${{ matrix.swift-version  }}
        uses: hdtls/setup-swift@main
        with: 
          swift-version: ${{matrix.swift-version}}
      
      - name: Build and test...
        run: swift test -Xswiftc -warnings-as-errors
