name: Unit tests

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-unit_tests
  cancel-in-progress: true

jobs:
  unit-tests:
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_windows_checks: true
      linux_exclude_swift_versions: "[{\"swift_version\": \"5.8\"}]"
      swift_flags: --explicit-target-dependency-import-check error
